### ISSUE TITLE
Feature Request - MAC Address Mask

### ISSUE THREAD

**Issue by biodrone** [Tombo1001/btlegeiger#4]
Hide annoying mac addresses which disrupt the debug process - noise filter.

**Comment by Tombo1001** [comment]
@biodrone do you still think this feature is required given the counter function, particularly with randomized ble MACs being part of the standard?

**Comment by biodrone** [comment]
@Tombo1001 Agreed, this will either be obsolete or we'll get around it a different way. Feel free to close this one.

**Comment by Tombo1001** [comment]
Feature no longer required.
